// custumer
export {default as Spalesh} from "./Spalesh";
export {default as Login} from "./Login/page";
export {default as Chat} from "./chat/page";
export {default as NoPage} from "./NoPage/page";
export {default as EditePassword} from "./EditePassword/page";
export {default as ForgetPassword} from "./ForjetPassword/page";
export {default as RestorePassword} from "./RestorePassword/page";

export {default as UsedWarning} from "./Forms/UsedWarning/page";
export {default as Khsosya} from "./Forms/Khsosya/page";
export {default as CustomerStartPage} from "./Customer/StartPage/page";
export {default as CustomerAccount} from "./Customer/Account/page";
export {default as CustomerAddRassed} from "./Customer/AddRassed/page";
export {default as CustomerSubscrib} from "./Customer/Subscrib/page";
export {default as CustomerNotes} from "./Customer/Notes/page";
export {default as CustomerKobon} from "./Customer/Kobon/page";
export {default as CustomerSupport} from "./Customer/Support/page";
export {default as CustomerAdressSaved} from "./Customer/AdressSaved/page";
export {default as CustomerAdressAdd} from "./Customer/AdressAdd/page";
export {default as CustomerAdressEdite} from "./Customer/AdressEdite/page";
export {default as CustomerAlert} from "./Customer/Alerts/page";
export {default as CustomerEditeProfile} from "./Customer/EditeProfile/page";
export {default as CustomerRegister} from "./Customer/Register/page";
export {default as CustomerOrders} from "./Customer/Orders/page";
export {default as CustomerOrderInfo} from "./Customer/OrderInfo/page";
export {default as CustomerShopping} from "./Customer/Shopping/page";
export {default as CustomerSearch} from "./Customer/Shopping/Search/page";
export {default as CustomerShoppingAnyThing} from "./Customer/Shopping/ShoppingAnyThing/page";
export {default as CustomerOrderWaiting} from "./Customer/Shopping/OrderWaiting/page";
export {default as CustomerOrderCancel} from "./Customer/Shopping/OrderCancel/page";

export {default as CustomerShoppingFrom} from "./Customer/Shopping/ShoppingFrom/page";
export {default as CustomerShoppingTo} from "./Customer/Shopping/ShoppingTo/page";
export {default as CustomerMain} from "./Customer/page";
export {default as CustomerSetting} from "./Customer/Setting/page";
export {default as CustomerHistoryShkawa} from "./Customer/HistoryShkawa/page";

// Deller
export {default as DellerAccount} from "./Deller/Account/page";
export {default as DellerAddRassed} from "./Deller/AddRassed/page";
export {default as DellerAlert} from "./Deller/Alerts/page";
export {default as DellerArbah} from "./Deller/Arbah/page";
export {default as DellerEditeProfile} from "./Deller/EditeProfile/page";
export {default as DellerKobon} from "./Deller/Kobon/page";
export {default as DellerMain} from "./Deller/Main/page";
export {default as DellerNotes} from "./Deller/Notes/page";
export {default as DellerOrders} from "./Deller/Orders/page";
export {default as DellerOrderInfo} from "./Deller/OrderInfo/page";
export {default as DellerRegister} from "./Deller/Register/page";
export {default as DellerReplaseAcount} from "./Deller/ReplaseAcount/page";
export {default as DellerSetting} from "./Deller/Setting/page";
export {default as DellerSupport} from "./Deller/Support/page";
export {default as DellerSubscrib} from "./Deller/Subscrib/page";
//=========================================================
export {default as AdminHome} from "./Admin/home/page";
export {default as AdminOrders} from "./Admin/Orders/page";
export {default as AdminCustomer} from "./Admin/Customer/page";
export {default as AdminEmpolyee} from "./Admin/Empolyee/page";
export {default as AdminDeller} from "./Admin/Deller/page";
export {default as AdminSetting} from "./Admin/Setting/page";
export {default as AdminShkawa} from "./Admin/Shkawa/page";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";
// export {default as AdminHome} from "./Admin/home";